### ISSUE TITLE
error on Android, Not a PKM file

### ISSUE THREAD

**Issue by kenaiX** [BinomialLLC/basis_universal#59]
```
//step1 init
basisu_transcoder_init();
if (!g_pGlobal_codebook)
    g_pGlobal_codebook = new basist::etc1_global_selector_codebook(g_global_selector_cb_size, g_global_selector_cb);
basisu_transcoder *m_transcoder = new basisu_transcoder(g_pGlobal_codebook);

//step2 get data from java
jbyte *bytedata = env->GetByteArrayElements(data, NULL);
jsize oldsize = env->GetArrayLength(data);

//step3 transcoding
uint32_t bytes_per_block = basis_get_bytes_per_block(cTFETC1);
uint32_t orig_width, orig_height, total_blocks;
if (!m_transcoder->get_image_level_desc(bytedata, oldsize, 0, 0, orig_width, orig_height, total_blocks))
    return env->NewByteArray(0);
m_transcoder->start_transcoding(bytedata, oldsize);

//step4 output to java
uint32_t required_size = total_blocks * bytes_per_block;
jbyteArray jbarray = env->NewByteArray(required_size);
jbyte *outdata = env->GetByteArrayElements(jbarray, NULL);

//logcat : b == true
bool b = m_transcoder->transcode_image_level(bytedata, oldsize, 0, 0, outdata, required_size / bytes_per_block , cTFETC1);

return jbarray;
```

transcode_image_level return true, but error when i use this etc byte[]

```
java.io.IOException: Not a PKM file.
W/System.err:     at android.opengl.ETC1Util.createTexture(ETC1Util.java:164)
W/System.err:     at android.opengl.ETC1Util.loadTexture(ETC1Util.java:48)
```

However when i use a normal ect file, everything ok

**Comment by kenaiX** [comment]
oh ETC1Util.loadTexture check pkm file.
so, should use ETC1Util.ETC1Texture

**Comment by Dip429** [comment]
i am getting the same error when trying to decompress it using the etcpack found in mali
